#Qual a imagem base desta imagem (alpine - imagem menor)
FROM openjdk:11
#Criando um usuario
USER gradle
##Criando um volume apontando para a pasta do gradle local
#VOLUME "/home/gradle/.gradle"
#WORKDIR /home/gradle
VOLUME "/home/gradle/.gradle"
WORKDIR /home/gradle
